name: CDK Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  cdk-diff:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    if: github.event.action != 'closed'
    steps:
      - uses: actions/checkout@v3

      - name: Check Environment Variables
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}"
          echo "SSH_ALLOWED_IPS: ${{ secrets.SSH_ALLOWED_IPS }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_CDK_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CDK_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.0"

      - name: Install dependencies
        run: npm ci

      - name: Set environment variables
        run: |
          echo "CERTIFICATE_ARN=${{ secrets.CERTIFICATE_ARN }}" >> $GITHUB_ENV
          echo "SSH_ALLOWED_IPS=${{ secrets.SSH_ALLOWED_IPS }}" >> $GITHUB_ENV

      - name: CDK Diff
        id: cdk-diff
        run: |
          diff=$(npx cdk diff -c environment=${{ inputs.environment }}) || true
          echo "$diff"
          echo "cdk_diff<<EOF" >> $GITHUB_OUTPUT
          echo "$diff" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const diff = `${{ steps.cdk-diff.outputs.cdk_diff }}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: diff ? `CDK Diff:\n\`\`\`\n${diff}\n\`\`\`` : "No changes"
            });

  cdk-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_CDK_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CDK_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.0"

      - name: Install dependencies
        run: npm ci

      - name: Set environment variables
        run: |
          echo "CERTIFICATE_ARN=${{ secrets.CERTIFICATE_ARN }}" >> $GITHUB_ENV
          echo "SSH_ALLOWED_IPS=${{ secrets.SSH_ALLOWED_IPS }}" >> $GITHUB_ENV

      - name: CDK Deploy
        run: npx cdk deploy -c environment=${{ inputs.environment }} --require-approval never
